apiVersion: apps/v1
kind: Deployment
metadata:
  name: notice-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notice
  template:
    metadata:
      name: notice-pod
      labels:
        app: notice
    spec:
      containers:
        - name: notice-run
          image: jdxj/notice:test-da9060c
          command: [ "/sign/notice.run" ]
          args: [ "--config", "/sign/config/conf.yaml" ]
          volumeMounts:
            - mountPath: /sign/config
              name: notice-conf
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: notice-conf
          secret:
            secretName: sign-config
