// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trigger/trigger.proto

package trigger

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Trigger struct {
	TriggerId            int64    `protobuf:"varint,1,opt,name=trigger_id,json=triggerId,proto3" json:"trigger_id,omitempty"`
	Spec                 string   `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trigger) Reset()         { *m = Trigger{} }
func (m *Trigger) String() string { return proto.CompactTextString(m) }
func (*Trigger) ProtoMessage()    {}
func (*Trigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_55ab2cdd0e1ab2b9, []int{0}
}

func (m *Trigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trigger.Unmarshal(m, b)
}
func (m *Trigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trigger.Marshal(b, m, deterministic)
}
func (m *Trigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trigger.Merge(m, src)
}
func (m *Trigger) XXX_Size() int {
	return xxx_messageInfo_Trigger.Size(m)
}
func (m *Trigger) XXX_DiscardUnknown() {
	xxx_messageInfo_Trigger.DiscardUnknown(m)
}

var xxx_messageInfo_Trigger proto.InternalMessageInfo

func (m *Trigger) GetTriggerId() int64 {
	if m != nil {
		return m.TriggerId
	}
	return 0
}

func (m *Trigger) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

type CreateTriggerRequest struct {
	Trigger              *Trigger `protobuf:"bytes,1,opt,name=trigger,proto3" json:"trigger,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTriggerRequest) Reset()         { *m = CreateTriggerRequest{} }
func (m *CreateTriggerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTriggerRequest) ProtoMessage()    {}
func (*CreateTriggerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55ab2cdd0e1ab2b9, []int{1}
}

func (m *CreateTriggerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTriggerRequest.Unmarshal(m, b)
}
func (m *CreateTriggerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTriggerRequest.Marshal(b, m, deterministic)
}
func (m *CreateTriggerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTriggerRequest.Merge(m, src)
}
func (m *CreateTriggerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTriggerRequest.Size(m)
}
func (m *CreateTriggerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTriggerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTriggerRequest proto.InternalMessageInfo

func (m *CreateTriggerRequest) GetTrigger() *Trigger {
	if m != nil {
		return m.Trigger
	}
	return nil
}

type GetTriggersRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTriggersRequest) Reset()         { *m = GetTriggersRequest{} }
func (m *GetTriggersRequest) String() string { return proto.CompactTextString(m) }
func (*GetTriggersRequest) ProtoMessage()    {}
func (*GetTriggersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55ab2cdd0e1ab2b9, []int{2}
}

func (m *GetTriggersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTriggersRequest.Unmarshal(m, b)
}
func (m *GetTriggersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTriggersRequest.Marshal(b, m, deterministic)
}
func (m *GetTriggersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTriggersRequest.Merge(m, src)
}
func (m *GetTriggersRequest) XXX_Size() int {
	return xxx_messageInfo_GetTriggersRequest.Size(m)
}
func (m *GetTriggersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTriggersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTriggersRequest proto.InternalMessageInfo

func (m *GetTriggersRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetTriggersRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetTriggersResponse struct {
	Count                int64      `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Triggers             []*Trigger `protobuf:"bytes,2,rep,name=triggers,proto3" json:"triggers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetTriggersResponse) Reset()         { *m = GetTriggersResponse{} }
func (m *GetTriggersResponse) String() string { return proto.CompactTextString(m) }
func (*GetTriggersResponse) ProtoMessage()    {}
func (*GetTriggersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_55ab2cdd0e1ab2b9, []int{3}
}

func (m *GetTriggersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTriggersResponse.Unmarshal(m, b)
}
func (m *GetTriggersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTriggersResponse.Marshal(b, m, deterministic)
}
func (m *GetTriggersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTriggersResponse.Merge(m, src)
}
func (m *GetTriggersResponse) XXX_Size() int {
	return xxx_messageInfo_GetTriggersResponse.Size(m)
}
func (m *GetTriggersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTriggersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTriggersResponse proto.InternalMessageInfo

func (m *GetTriggersResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetTriggersResponse) GetTriggers() []*Trigger {
	if m != nil {
		return m.Triggers
	}
	return nil
}

func init() {
	proto.RegisterType((*Trigger)(nil), "Trigger")
	proto.RegisterType((*CreateTriggerRequest)(nil), "CreateTriggerRequest")
	proto.RegisterType((*GetTriggersRequest)(nil), "GetTriggersRequest")
	proto.RegisterType((*GetTriggersResponse)(nil), "GetTriggersResponse")
}

func init() { proto.RegisterFile("trigger/trigger.proto", fileDescriptor_55ab2cdd0e1ab2b9) }

var fileDescriptor_55ab2cdd0e1ab2b9 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4b, 0x4b, 0x33, 0x31,
	0x14, 0x65, 0xda, 0xef, 0xeb, 0xe3, 0x16, 0x5d, 0xa4, 0x0f, 0x4a, 0x45, 0x28, 0x83, 0x8b, 0x82,
	0x98, 0x40, 0xdd, 0x88, 0x88, 0x8b, 0x8a, 0x88, 0x4b, 0x47, 0x57, 0x6e, 0xa4, 0x9d, 0xb9, 0x13,
	0x53, 0x66, 0x26, 0x63, 0x92, 0x11, 0xfd, 0x0b, 0xfe, 0x6a, 0xe9, 0x24, 0x11, 0x07, 0xbb, 0x4a,
	0xce, 0x7d, 0x9c, 0x7b, 0xcf, 0xb9, 0x30, 0x36, 0x4a, 0x70, 0x8e, 0x8a, 0xb9, 0x97, 0x96, 0x4a,
	0x1a, 0x39, 0x3b, 0xe2, 0x52, 0xf2, 0x0c, 0x59, 0x8d, 0x36, 0x55, 0xca, 0x30, 0x2f, 0xcd, 0xa7,
	0x4d, 0x86, 0x57, 0xd0, 0x7d, 0xb2, 0xd5, 0xe4, 0x18, 0xc0, 0x35, 0xbe, 0x88, 0x64, 0x1a, 0xcc,
	0x83, 0x45, 0x3b, 0xea, 0xbb, 0xc8, 0x7d, 0x42, 0x08, 0xfc, 0xd3, 0x25, 0xc6, 0xd3, 0xd6, 0x3c,
	0x58, 0xf4, 0xa3, 0xfa, 0x1f, 0x5e, 0xc2, 0xe8, 0x46, 0xe1, 0xda, 0xa0, 0xe3, 0x88, 0xf0, 0xad,
	0x42, 0x6d, 0x48, 0x08, 0x5d, 0xd7, 0x58, 0xf3, 0x0c, 0x96, 0x3d, 0xea, 0x2b, 0x7c, 0x22, 0x5c,
	0x01, 0xb9, 0x43, 0xe3, 0xc2, 0xda, 0x77, 0x4e, 0xa0, 0x23, 0xd3, 0x54, 0xa3, 0x71, 0x0b, 0x38,
	0x44, 0x46, 0xf0, 0x3f, 0x13, 0xb9, 0x30, 0xf5, 0xf8, 0x76, 0x64, 0x41, 0xf8, 0x00, 0xc3, 0x06,
	0x87, 0x2e, 0x65, 0xa1, 0x71, 0x57, 0x1c, 0xcb, 0xaa, 0xf0, 0x1c, 0x16, 0x90, 0x13, 0xe8, 0xb9,
	0xd9, 0x7a, 0xda, 0x9a, 0xb7, 0x1b, 0x5b, 0xfd, 0x64, 0x96, 0x5f, 0x01, 0x1c, 0xba, 0xe8, 0x23,
	0xaa, 0x77, 0x11, 0x23, 0xb9, 0x86, 0x83, 0x86, 0x4a, 0x32, 0xa6, 0xfb, 0x54, 0xcf, 0x26, 0xd4,
	0x3a, 0x4d, 0xbd, 0xd3, 0xf4, 0x76, 0xe7, 0x34, 0xb9, 0x80, 0xc1, 0xaf, 0x2d, 0xc9, 0x90, 0xfe,
	0xd5, 0x3d, 0x1b, 0xd1, 0x3d, 0x42, 0x56, 0x67, 0xcf, 0xa7, 0x5c, 0x98, 0xd7, 0x6a, 0x43, 0x63,
	0x99, 0xb3, 0x6d, 0xf2, 0xb1, 0x65, 0x5a, 0xf0, 0x82, 0x89, 0xc2, 0xa0, 0x2a, 0xd6, 0x99, 0xbd,
	0xa9, 0xbf, 0xf7, 0xa6, 0x53, 0xc3, 0xf3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0x70, 0xa2,
	0x0a, 0x09, 0x02, 0x00, 0x00,
}
