# kubectl create/apply -f dep.yaml --record

# 查看部署状态
# kubectl rollout status deployment apiserver

# 升级
# kubectl set image deployment dep container=image:tag
# 回滚, 取消最后一次部署
# kubectl rollout undo deployment dep

# 升级历史
# kubectl rollout history deployment dep
# 回滚到特定版本
# kubectl rollout undo deployment dep --to-revision=1

# 暂停滚动升级
# kubectl rollout pause deployment dep
# 恢复滚动升级
# kubectl rollout resume deployment dep

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      name: apiserver-pod
      labels:
        app: apiserver
    spec:
      containers:
        - name: apiserver
          image: jdxj/sign:v0.1
          command: ["/sign/apiserver.out"]
          args: ["-f", "/sign/config/config.yaml"]
          env:
            - name: GIN_MODE
              value: release
          volumeMounts:
            - mountPath: /sign/bak_log # 挂载点, 备份路径
              name: apiserver-bak-log  # 要使用的卷的卷名
            - mountPath: /sign/config
              name: apiserver-config
          ports:
            - containerPort: 8081
              protocol: TCP
      volumes:
        - name: apiserver-bak-log
          persistentVolumeClaim:
            claimName: apiserver-pvc
        - name: apiserver-config
          configMap:
            name: apiserver-cm