# kubectl create/apply -f dep.yaml --record

# 查看部署状态
# kubectl rollout status deployment apiserver

# 升级
# kubectl set image deployment dep container=image:tag
# 回滚, 取消最后一次部署
# kubectl rollout undo deployment dep

# 升级历史
# kubectl rollout history deployment dep
# 回滚到特定版本
# kubectl rollout undo deployment dep --to-revision=1

# 暂停滚动升级
# kubectl rollout pause deployment dep
# 恢复滚动升级
# kubectl rollout resume deployment dep

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dep
  namespace: sign
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      name: app-pod
      labels:
        app: app
    spec:
      containers:
        - name: app-run
          image: jdxj/app:v0.11.1
          command: [ "/sign/app.run" ]
          args: [ "--config", "/sign/config/conf.yaml" ]
          env:
            - name: GIN_MODE
              value: release
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: /sign/config
              name: app-conf
          ports:
            - containerPort: 8080
              protocol: TCP
      volumes:
        - name: app-conf
          secret:
            secretName: sign-config
