// Code generated by "sign/tools/code"; DO NOT EDIT.

package sign_error

func init() {
	register(500, ErrUnknown, "unknown error")
	register(400, ErrBindRequest, "parse request failed")
	register(500, ErrRPCCall, "rpc call failed")
	register(400, ErrLogin, "login failed")
	register(400, ErrAuth, "auth failed")
	register(400, ErrEncodeParam, "encode param failed")
	register(500, ErrDecodeParam, "decode param failed")
}
