// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test-grpc/hello.proto

package test_grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReq) Reset()         { *m = HelloReq{} }
func (m *HelloReq) String() string { return proto.CompactTextString(m) }
func (*HelloReq) ProtoMessage()    {}
func (*HelloReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e1454f155b02984, []int{0}
}

func (m *HelloReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReq.Unmarshal(m, b)
}
func (m *HelloReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReq.Marshal(b, m, deterministic)
}
func (m *HelloReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReq.Merge(m, src)
}
func (m *HelloReq) XXX_Size() int {
	return xxx_messageInfo_HelloReq.Size(m)
}
func (m *HelloReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReq.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReq proto.InternalMessageInfo

func (m *HelloReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloRsp struct {
	Age                  int64    `protobuf:"varint,2,opt,name=Age,proto3" json:"Age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRsp) Reset()         { *m = HelloRsp{} }
func (m *HelloRsp) String() string { return proto.CompactTextString(m) }
func (*HelloRsp) ProtoMessage()    {}
func (*HelloRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e1454f155b02984, []int{1}
}

func (m *HelloRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRsp.Unmarshal(m, b)
}
func (m *HelloRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRsp.Marshal(b, m, deterministic)
}
func (m *HelloRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRsp.Merge(m, src)
}
func (m *HelloRsp) XXX_Size() int {
	return xxx_messageInfo_HelloRsp.Size(m)
}
func (m *HelloRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRsp.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRsp proto.InternalMessageInfo

func (m *HelloRsp) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

type WorldReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorldReq) Reset()         { *m = WorldReq{} }
func (m *WorldReq) String() string { return proto.CompactTextString(m) }
func (*WorldReq) ProtoMessage()    {}
func (*WorldReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e1454f155b02984, []int{2}
}

func (m *WorldReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldReq.Unmarshal(m, b)
}
func (m *WorldReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldReq.Marshal(b, m, deterministic)
}
func (m *WorldReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldReq.Merge(m, src)
}
func (m *WorldReq) XXX_Size() int {
	return xxx_messageInfo_WorldReq.Size(m)
}
func (m *WorldReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldReq.DiscardUnknown(m)
}

var xxx_messageInfo_WorldReq proto.InternalMessageInfo

func (m *WorldReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type WorldRsp struct {
	Age                  int64    `protobuf:"varint,2,opt,name=Age,proto3" json:"Age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorldRsp) Reset()         { *m = WorldRsp{} }
func (m *WorldRsp) String() string { return proto.CompactTextString(m) }
func (*WorldRsp) ProtoMessage()    {}
func (*WorldRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e1454f155b02984, []int{3}
}

func (m *WorldRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorldRsp.Unmarshal(m, b)
}
func (m *WorldRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorldRsp.Marshal(b, m, deterministic)
}
func (m *WorldRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorldRsp.Merge(m, src)
}
func (m *WorldRsp) XXX_Size() int {
	return xxx_messageInfo_WorldRsp.Size(m)
}
func (m *WorldRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_WorldRsp.DiscardUnknown(m)
}

var xxx_messageInfo_WorldRsp proto.InternalMessageInfo

func (m *WorldRsp) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloReq)(nil), "HelloReq")
	proto.RegisterType((*HelloRsp)(nil), "HelloRsp")
	proto.RegisterType((*WorldReq)(nil), "WorldReq")
	proto.RegisterType((*WorldRsp)(nil), "WorldRsp")
}

func init() { proto.RegisterFile("test-grpc/hello.proto", fileDescriptor_3e1454f155b02984) }

var fileDescriptor_3e1454f155b02984 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x49, 0x2d, 0x2e,
	0xd1, 0x4d, 0x2f, 0x2a, 0x48, 0xd6, 0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x57, 0x92, 0xe3, 0xe2, 0xf0, 0x00, 0x71, 0x83, 0x52, 0x0b, 0x85, 0x84, 0xb8, 0x58, 0xfc,
	0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x19, 0x98, 0x7c,
	0x71, 0x81, 0x90, 0x00, 0x17, 0xb3, 0x63, 0x7a, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x73, 0x10,
	0x88, 0x09, 0xd2, 0x1d, 0x9e, 0x5f, 0x94, 0x93, 0x82, 0x47, 0x37, 0x44, 0x1e, 0x9b, 0x6e, 0x23,
	0x0d, 0x2e, 0xf6, 0x90, 0xd4, 0xe2, 0x92, 0xa0, 0x00, 0x67, 0x21, 0x59, 0x2e, 0x56, 0xb0, 0x35,
	0x42, 0x9c, 0x7a, 0x30, 0xe7, 0x48, 0xc1, 0x98, 0xc5, 0x05, 0x46, 0xba, 0x5c, 0x3c, 0x20, 0x95,
	0xbe, 0xa5, 0x39, 0x25, 0x99, 0x50, 0xe5, 0x60, 0x73, 0x85, 0x38, 0xf5, 0x60, 0xf6, 0x4b, 0xc1,
	0x98, 0xc5, 0x05, 0x4e, 0xfa, 0x51, 0xba, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9,
	0xb9, 0xfa, 0x59, 0x29, 0x15, 0x59, 0xfa, 0xc5, 0x99, 0xe9, 0x79, 0xfa, 0x99, 0x79, 0x25, 0xa9,
	0x45, 0x79, 0x89, 0x39, 0xfa, 0x60, 0xbf, 0xeb, 0x83, 0x42, 0x24, 0x1e, 0x14, 0x22, 0x49, 0x6c,
	0x60, 0x01, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x85, 0xc3, 0xd3, 0xe1, 0x25, 0x01, 0x00,
	0x00,
}
