apiVersion: apps/v1
kind: Deployment
metadata:
  name: trigger-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trigger
  template:
    metadata:
      name: trigger-pod
      labels:
        app: trigger
    spec:
      containers:
        - name: trigger-run
          image: jdxj/trigger:test-da9060c
          command: [ "/sign/trigger.run" ]
          args: [ "--config", "/sign/config/conf.yaml" ]
          volumeMounts:
            - mountPath: /sign/config
              name: trigger-conf
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: trigger-conf
          secret:
            secretName: sign-config
