// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthUserReq struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthUserReq) Reset()         { *m = AuthUserReq{} }
func (m *AuthUserReq) String() string { return proto.CompactTextString(m) }
func (*AuthUserReq) ProtoMessage()    {}
func (*AuthUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{0}
}

func (m *AuthUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthUserReq.Unmarshal(m, b)
}
func (m *AuthUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthUserReq.Marshal(b, m, deterministic)
}
func (m *AuthUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthUserReq.Merge(m, src)
}
func (m *AuthUserReq) XXX_Size() int {
	return xxx_messageInfo_AuthUserReq.Size(m)
}
func (m *AuthUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthUserReq proto.InternalMessageInfo

func (m *AuthUserReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *AuthUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthUserRsp struct {
	Valid                bool     `protobuf:"varint,1,opt,name=Valid,proto3" json:"Valid,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthUserRsp) Reset()         { *m = AuthUserRsp{} }
func (m *AuthUserRsp) String() string { return proto.CompactTextString(m) }
func (*AuthUserRsp) ProtoMessage()    {}
func (*AuthUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{1}
}

func (m *AuthUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthUserRsp.Unmarshal(m, b)
}
func (m *AuthUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthUserRsp.Marshal(b, m, deterministic)
}
func (m *AuthUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthUserRsp.Merge(m, src)
}
func (m *AuthUserRsp) XXX_Size() int {
	return xxx_messageInfo_AuthUserRsp.Size(m)
}
func (m *AuthUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthUserRsp proto.InternalMessageInfo

func (m *AuthUserRsp) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *AuthUserRsp) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type CreateUserReq struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReq) Reset()         { *m = CreateUserReq{} }
func (m *CreateUserReq) String() string { return proto.CompactTextString(m) }
func (*CreateUserReq) ProtoMessage()    {}
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{2}
}

func (m *CreateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReq.Unmarshal(m, b)
}
func (m *CreateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReq.Marshal(b, m, deterministic)
}
func (m *CreateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReq.Merge(m, src)
}
func (m *CreateUserReq) XXX_Size() int {
	return xxx_messageInfo_CreateUserReq.Size(m)
}
func (m *CreateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReq proto.InternalMessageInfo

func (m *CreateUserReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserRsp struct {
	UserID               int64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRsp) Reset()         { *m = CreateUserRsp{} }
func (m *CreateUserRsp) String() string { return proto.CompactTextString(m) }
func (*CreateUserRsp) ProtoMessage()    {}
func (*CreateUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{3}
}

func (m *CreateUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRsp.Unmarshal(m, b)
}
func (m *CreateUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRsp.Marshal(b, m, deterministic)
}
func (m *CreateUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRsp.Merge(m, src)
}
func (m *CreateUserRsp) XXX_Size() int {
	return xxx_messageInfo_CreateUserRsp.Size(m)
}
func (m *CreateUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRsp proto.InternalMessageInfo

func (m *CreateUserRsp) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetUserReq struct {
	UserID               int64    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserReq) Reset()         { *m = GetUserReq{} }
func (m *GetUserReq) String() string { return proto.CompactTextString(m) }
func (*GetUserReq) ProtoMessage()    {}
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{4}
}

func (m *GetUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReq.Unmarshal(m, b)
}
func (m *GetUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReq.Marshal(b, m, deterministic)
}
func (m *GetUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReq.Merge(m, src)
}
func (m *GetUserReq) XXX_Size() int {
	return xxx_messageInfo_GetUserReq.Size(m)
}
func (m *GetUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReq proto.InternalMessageInfo

func (m *GetUserReq) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetUserRsp struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRsp) Reset()         { *m = GetUserRsp{} }
func (m *GetUserRsp) String() string { return proto.CompactTextString(m) }
func (*GetUserRsp) ProtoMessage()    {}
func (*GetUserRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{5}
}

func (m *GetUserRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRsp.Unmarshal(m, b)
}
func (m *GetUserRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRsp.Marshal(b, m, deterministic)
}
func (m *GetUserRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRsp.Merge(m, src)
}
func (m *GetUserRsp) XXX_Size() int {
	return xxx_messageInfo_GetUserRsp.Size(m)
}
func (m *GetUserRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRsp proto.InternalMessageInfo

func (m *GetUserRsp) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetUserRsp) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthUserReq)(nil), "AuthUserReq")
	proto.RegisterType((*AuthUserRsp)(nil), "AuthUserRsp")
	proto.RegisterType((*CreateUserReq)(nil), "CreateUserReq")
	proto.RegisterType((*CreateUserRsp)(nil), "CreateUserRsp")
	proto.RegisterType((*GetUserReq)(nil), "GetUserReq")
	proto.RegisterType((*GetUserRsp)(nil), "GetUserRsp")
}

func init() { proto.RegisterFile("user/user.proto", fileDescriptor_ed89022014131a74) }

var fileDescriptor_ed89022014131a74 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2d, 0x4e, 0x2d,
	0xd2, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x4a, 0xae, 0x5c, 0xdc, 0x8e, 0xa5, 0x25,
	0x19, 0xa1, 0xc5, 0xa9, 0x45, 0x41, 0xa9, 0x85, 0x42, 0x52, 0x5c, 0x1c, 0x7e, 0x99, 0xc9, 0xd9,
	0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0x3e, 0x48, 0x2e, 0x20,
	0xb1, 0xb8, 0xb8, 0x3c, 0xbf, 0x28, 0x45, 0x82, 0x09, 0x22, 0x07, 0xe3, 0x2b, 0x59, 0x23, 0x19,
	0x53, 0x5c, 0x20, 0x24, 0xc2, 0xc5, 0x1a, 0x96, 0x98, 0x93, 0x99, 0x02, 0x36, 0x83, 0x23, 0x08,
	0xc2, 0x11, 0x12, 0xe3, 0x62, 0x03, 0x29, 0xf0, 0x74, 0x01, 0x6b, 0x67, 0x0e, 0x82, 0xf2, 0x94,
	0xdc, 0xb9, 0x78, 0x9d, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x29, 0x75, 0x85, 0x3a, 0x8a, 0x41, 0xc5,
	0x05, 0x48, 0x36, 0x32, 0xa2, 0xd8, 0xa8, 0xc2, 0xc5, 0xe5, 0x9e, 0x5a, 0x02, 0xb3, 0x0e, 0x97,
	0x2a, 0x17, 0x84, 0xaa, 0xe2, 0x02, 0x72, 0x1d, 0x65, 0xd4, 0xc1, 0xc8, 0xc5, 0x0d, 0x32, 0x23,
	0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0x48, 0x8d, 0x8b, 0x03, 0x16, 0x54, 0x42, 0x3c, 0x7a,
	0x48, 0x81, 0x2f, 0x85, 0xc4, 0x2b, 0x2e, 0x10, 0xd2, 0xe1, 0xe2, 0x42, 0x78, 0x46, 0x88, 0x4f,
	0x0f, 0x25, 0x88, 0xa4, 0x50, 0xf8, 0xc5, 0x05, 0x42, 0xca, 0x5c, 0xec, 0x50, 0xb7, 0x0a, 0x71,
	0xeb, 0x21, 0xfc, 0x26, 0x85, 0xe0, 0x14, 0x17, 0x38, 0x69, 0x45, 0x69, 0xa4, 0x67, 0x96, 0x64,
	0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x67, 0xa5, 0x54, 0x64, 0xe9, 0x17, 0x67, 0xa6, 0xe7,
	0xe9, 0x67, 0xe6, 0x95, 0xa4, 0x16, 0xe5, 0x25, 0xe6, 0xe8, 0x83, 0xd3, 0x04, 0x38, 0x79, 0x24,
	0xb1, 0x81, 0xd9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x38, 0xd9, 0x30, 0x32, 0x02,
	0x00, 0x00,
}
