apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      name: user-pod
      labels:
        app: user
    spec:
      containers:
        - name: user-run
          image: jdxj/user:test-da9060c
          command: [ "/sign/user.run" ]
          args: [ "--config", "/sign/config/conf.yaml" ]
          volumeMounts:
            - mountPath: /sign/config
              name: user-conf
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: user-conf
          secret:
            secretName: sign-config
