// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: app/app.proto

package app

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AppService service

func NewAppServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for AppService service

type AppService interface {
	Version(ctx context.Context, in *emptypb.Empty, opts ...client.CallOption) (*VersionResponse, error)
}

type appService struct {
	c    client.Client
	name string
}

func NewAppService(name string, c client.Client) AppService {
	return &appService{
		c:    c,
		name: name,
	}
}

func (c *appService) Version(ctx context.Context, in *emptypb.Empty, opts ...client.CallOption) (*VersionResponse, error) {
	req := c.c.NewRequest(c.name, "AppService.Version", in)
	out := new(VersionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AppService service

type AppServiceHandler interface {
	Version(context.Context, *emptypb.Empty, *VersionResponse) error
}

func RegisterAppServiceHandler(s server.Server, hdlr AppServiceHandler, opts ...server.HandlerOption) error {
	type appService interface {
		Version(ctx context.Context, in *emptypb.Empty, out *VersionResponse) error
	}
	type AppService struct {
		appService
	}
	h := &appServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&AppService{h}, opts...))
}

type appServiceHandler struct {
	AppServiceHandler
}

func (h *appServiceHandler) Version(ctx context.Context, in *emptypb.Empty, out *VersionResponse) error {
	return h.AppServiceHandler.Version(ctx, in, out)
}
