# kubectl create/apply -f dep.yaml --record

# 查看部署状态
# kubectl rollout status deployment apiserver

# 升级
# kubectl set image deployment dep container=image:tag
# 回滚, 取消最后一次部署
# kubectl rollout undo deployment dep

# 升级历史
# kubectl rollout history deployment dep
# 回滚到特定版本
# kubectl rollout undo deployment dep --to-revision=1

# 暂停滚动升级
# kubectl rollout pause deployment dep
# 恢复滚动升级
# kubectl rollout resume deployment dep

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notice-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notice
  template:
    metadata:
      name: notice-pod
      labels:
        app: notice
    spec:
      containers:
        - name: notice-run
          image: jdxj/notice:test-2e85bdf
          command: [ "/sign/notice.run" ]
          args: [ "--config", "/sign/config/conf.yaml" ]
          volumeMounts:
            - mountPath: /sign/config
              name: notice-conf
      volumes:
        - name: notice-conf
          secret:
            secretName: sign-config
