// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task/task.proto

package task

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Kind 使用时要用字符串形式
type Kind int32

const (
	Kind_UNKNOWN_KIND Kind = 0
	// B站
	Kind_BILIBILI_SIGN_IN Kind = 1
	Kind_BILIBILI_B_COUNT Kind = 2
	// Go语言中文网
	Kind_STG_SIGN_IN Kind = 3
	// V2ex
	Kind_V2EX_SIGN_IN Kind = 4
	// Evolution X
	Kind_RAPHAEL Kind = 5
	Kind_RELEASE Kind = 6
	// 掘金签到
	Kind_JUEJIN_Sign_IN Kind = 7
	// 签到天数统计
	Kind_JUEJIN_COUNT Kind = 8
	// 矿石数
	Kind_JUEJIN_POINT Kind = 9
	// 码农日历
	Kind_JUEJIN_CALENDAR Kind = 10
	// 自定义消息
	Kind_CUSTOM_MESSAGE Kind = 11
)

var Kind_name = map[int32]string{
	0:  "UNKNOWN_KIND",
	1:  "BILIBILI_SIGN_IN",
	2:  "BILIBILI_B_COUNT",
	3:  "STG_SIGN_IN",
	4:  "V2EX_SIGN_IN",
	5:  "RAPHAEL",
	6:  "RELEASE",
	7:  "JUEJIN_Sign_IN",
	8:  "JUEJIN_COUNT",
	9:  "JUEJIN_POINT",
	10: "JUEJIN_CALENDAR",
	11: "CUSTOM_MESSAGE",
}

var Kind_value = map[string]int32{
	"UNKNOWN_KIND":     0,
	"BILIBILI_SIGN_IN": 1,
	"BILIBILI_B_COUNT": 2,
	"STG_SIGN_IN":      3,
	"V2EX_SIGN_IN":     4,
	"RAPHAEL":          5,
	"RELEASE":          6,
	"JUEJIN_Sign_IN":   7,
	"JUEJIN_COUNT":     8,
	"JUEJIN_POINT":     9,
	"JUEJIN_CALENDAR":  10,
	"CUSTOM_MESSAGE":   11,
}

func (x Kind) String() string {
	return proto.EnumName(Kind_name, int32(x))
}

func (Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{0}
}

type Task struct {
	TaskId               int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UserId               int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Kind                 string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Spec                 string                 `protobuf:"bytes,5,opt,name=spec,proto3" json:"spec,omitempty"`
	Param                []byte                 `protobuf:"bytes,6,opt,name=param,proto3" json:"param,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Task) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Task) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *Task) GetParam() []byte {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *Task) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateTaskRequest struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskRequest) Reset()         { *m = CreateTaskRequest{} }
func (m *CreateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTaskRequest) ProtoMessage()    {}
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{1}
}

func (m *CreateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskRequest.Unmarshal(m, b)
}
func (m *CreateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskRequest.Marshal(b, m, deterministic)
}
func (m *CreateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskRequest.Merge(m, src)
}
func (m *CreateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTaskRequest.Size(m)
}
func (m *CreateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskRequest proto.InternalMessageInfo

func (m *CreateTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type CreateTaskResponse struct {
	TaskId               int64    `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskResponse) Reset()         { *m = CreateTaskResponse{} }
func (m *CreateTaskResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTaskResponse) ProtoMessage()    {}
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{2}
}

func (m *CreateTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskResponse.Unmarshal(m, b)
}
func (m *CreateTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskResponse.Marshal(b, m, deterministic)
}
func (m *CreateTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskResponse.Merge(m, src)
}
func (m *CreateTaskResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTaskResponse.Size(m)
}
func (m *CreateTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskResponse proto.InternalMessageInfo

func (m *CreateTaskResponse) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type GetTaskRequest struct {
	TaskId               int64    `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskRequest) Reset()         { *m = GetTaskRequest{} }
func (m *GetTaskRequest) String() string { return proto.CompactTextString(m) }
func (*GetTaskRequest) ProtoMessage()    {}
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{3}
}

func (m *GetTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskRequest.Unmarshal(m, b)
}
func (m *GetTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskRequest.Marshal(b, m, deterministic)
}
func (m *GetTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskRequest.Merge(m, src)
}
func (m *GetTaskRequest) XXX_Size() int {
	return xxx_messageInfo_GetTaskRequest.Size(m)
}
func (m *GetTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskRequest proto.InternalMessageInfo

func (m *GetTaskRequest) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type GetTaskResponse struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTaskResponse) Reset()         { *m = GetTaskResponse{} }
func (m *GetTaskResponse) String() string { return proto.CompactTextString(m) }
func (*GetTaskResponse) ProtoMessage()    {}
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{4}
}

func (m *GetTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTaskResponse.Unmarshal(m, b)
}
func (m *GetTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTaskResponse.Marshal(b, m, deterministic)
}
func (m *GetTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTaskResponse.Merge(m, src)
}
func (m *GetTaskResponse) XXX_Size() int {
	return xxx_messageInfo_GetTaskResponse.Size(m)
}
func (m *GetTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTaskResponse proto.InternalMessageInfo

func (m *GetTaskResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type GetTasksRequest struct {
	TaskId               int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Description          string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UserId               int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Kind                 string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Spec                 string                 `protobuf:"bytes,5,opt,name=spec,proto3" json:"spec,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Offset               int64                  `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64                  `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetTasksRequest) Reset()         { *m = GetTasksRequest{} }
func (m *GetTasksRequest) String() string { return proto.CompactTextString(m) }
func (*GetTasksRequest) ProtoMessage()    {}
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{5}
}

func (m *GetTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTasksRequest.Unmarshal(m, b)
}
func (m *GetTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTasksRequest.Marshal(b, m, deterministic)
}
func (m *GetTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTasksRequest.Merge(m, src)
}
func (m *GetTasksRequest) XXX_Size() int {
	return xxx_messageInfo_GetTasksRequest.Size(m)
}
func (m *GetTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTasksRequest proto.InternalMessageInfo

func (m *GetTasksRequest) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *GetTasksRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetTasksRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetTasksRequest) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *GetTasksRequest) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

func (m *GetTasksRequest) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *GetTasksRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetTasksRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetTasksResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Tasks                []*Task  `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTasksResponse) Reset()         { *m = GetTasksResponse{} }
func (m *GetTasksResponse) String() string { return proto.CompactTextString(m) }
func (*GetTasksResponse) ProtoMessage()    {}
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{6}
}

func (m *GetTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTasksResponse.Unmarshal(m, b)
}
func (m *GetTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTasksResponse.Marshal(b, m, deterministic)
}
func (m *GetTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTasksResponse.Merge(m, src)
}
func (m *GetTasksResponse) XXX_Size() int {
	return xxx_messageInfo_GetTasksResponse.Size(m)
}
func (m *GetTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTasksResponse proto.InternalMessageInfo

func (m *GetTasksResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetTasksResponse) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

type UpdateTaskRequest struct {
	TaskId               int64    `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskRequest) Reset()         { *m = UpdateTaskRequest{} }
func (m *UpdateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskRequest) ProtoMessage()    {}
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{7}
}

func (m *UpdateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskRequest.Unmarshal(m, b)
}
func (m *UpdateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskRequest.Merge(m, src)
}
func (m *UpdateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskRequest.Size(m)
}
func (m *UpdateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskRequest proto.InternalMessageInfo

func (m *UpdateTaskRequest) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *UpdateTaskRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetKindsResponse struct {
	Kinds                []string `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKindsResponse) Reset()         { *m = GetKindsResponse{} }
func (m *GetKindsResponse) String() string { return proto.CompactTextString(m) }
func (*GetKindsResponse) ProtoMessage()    {}
func (*GetKindsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{8}
}

func (m *GetKindsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKindsResponse.Unmarshal(m, b)
}
func (m *GetKindsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKindsResponse.Marshal(b, m, deterministic)
}
func (m *GetKindsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKindsResponse.Merge(m, src)
}
func (m *GetKindsResponse) XXX_Size() int {
	return xxx_messageInfo_GetKindsResponse.Size(m)
}
func (m *GetKindsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKindsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetKindsResponse proto.InternalMessageInfo

func (m *GetKindsResponse) GetKinds() []string {
	if m != nil {
		return m.Kinds
	}
	return nil
}

type DispatchTasksRequest struct {
	Spec                 string   `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DispatchTasksRequest) Reset()         { *m = DispatchTasksRequest{} }
func (m *DispatchTasksRequest) String() string { return proto.CompactTextString(m) }
func (*DispatchTasksRequest) ProtoMessage()    {}
func (*DispatchTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{9}
}

func (m *DispatchTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DispatchTasksRequest.Unmarshal(m, b)
}
func (m *DispatchTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DispatchTasksRequest.Marshal(b, m, deterministic)
}
func (m *DispatchTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DispatchTasksRequest.Merge(m, src)
}
func (m *DispatchTasksRequest) XXX_Size() int {
	return xxx_messageInfo_DispatchTasksRequest.Size(m)
}
func (m *DispatchTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DispatchTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DispatchTasksRequest proto.InternalMessageInfo

func (m *DispatchTasksRequest) GetSpec() string {
	if m != nil {
		return m.Spec
	}
	return ""
}

type ReadyTasks struct {
	Tasks                []*Task  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadyTasks) Reset()         { *m = ReadyTasks{} }
func (m *ReadyTasks) String() string { return proto.CompactTextString(m) }
func (*ReadyTasks) ProtoMessage()    {}
func (*ReadyTasks) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e8f2b86464a95fe, []int{10}
}

func (m *ReadyTasks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadyTasks.Unmarshal(m, b)
}
func (m *ReadyTasks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadyTasks.Marshal(b, m, deterministic)
}
func (m *ReadyTasks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadyTasks.Merge(m, src)
}
func (m *ReadyTasks) XXX_Size() int {
	return xxx_messageInfo_ReadyTasks.Size(m)
}
func (m *ReadyTasks) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadyTasks.DiscardUnknown(m)
}

var xxx_messageInfo_ReadyTasks proto.InternalMessageInfo

func (m *ReadyTasks) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func init() {
	proto.RegisterEnum("Kind", Kind_name, Kind_value)
	proto.RegisterType((*Task)(nil), "Task")
	proto.RegisterType((*CreateTaskRequest)(nil), "CreateTaskRequest")
	proto.RegisterType((*CreateTaskResponse)(nil), "CreateTaskResponse")
	proto.RegisterType((*GetTaskRequest)(nil), "GetTaskRequest")
	proto.RegisterType((*GetTaskResponse)(nil), "GetTaskResponse")
	proto.RegisterType((*GetTasksRequest)(nil), "GetTasksRequest")
	proto.RegisterType((*GetTasksResponse)(nil), "GetTasksResponse")
	proto.RegisterType((*UpdateTaskRequest)(nil), "UpdateTaskRequest")
	proto.RegisterType((*GetKindsResponse)(nil), "GetKindsResponse")
	proto.RegisterType((*DispatchTasksRequest)(nil), "DispatchTasksRequest")
	proto.RegisterType((*ReadyTasks)(nil), "ReadyTasks")
}

func init() { proto.RegisterFile("task/task.proto", fileDescriptor_8e8f2b86464a95fe) }

var fileDescriptor_8e8f2b86464a95fe = []byte{
	// 712 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcd, 0x4e, 0xdb, 0x4a,
	0x18, 0xbd, 0xce, 0x2f, 0xf9, 0xc2, 0x25, 0x66, 0xc8, 0xe5, 0xba, 0x61, 0xd1, 0xc8, 0xab, 0x80,
	0xe8, 0x44, 0x4a, 0x85, 0xd4, 0x6e, 0x2a, 0x05, 0xb0, 0x52, 0x43, 0x70, 0x90, 0x9d, 0xb4, 0x55,
	0x37, 0x96, 0x89, 0x87, 0x30, 0x40, 0x6c, 0x37, 0x33, 0xa9, 0xca, 0x73, 0xb6, 0x4f, 0xd0, 0x87,
	0xe8, 0xba, 0x9a, 0xb1, 0xf3, 0x63, 0x42, 0x5a, 0x75, 0xd3, 0x05, 0x68, 0xce, 0x99, 0x33, 0xdf,
	0xcc, 0xf9, 0x7e, 0x62, 0xa8, 0x70, 0x8f, 0xdd, 0x35, 0xc5, 0x3f, 0x1c, 0x4d, 0x42, 0x1e, 0xd6,
	0x9e, 0x8f, 0xc2, 0x70, 0x74, 0x4f, 0x9a, 0x12, 0x5d, 0x4d, 0xaf, 0x9b, 0x9c, 0x8e, 0x09, 0xe3,
	0xde, 0x38, 0x4a, 0x04, 0x7b, 0x8f, 0x05, 0x64, 0x1c, 0xf1, 0x87, 0x78, 0x53, 0xff, 0xaa, 0x40,
	0xae, 0xef, 0xb1, 0x3b, 0xf4, 0x3f, 0x14, 0x45, 0x50, 0x97, 0xfa, 0x9a, 0x52, 0x57, 0x1a, 0x59,
	0xbb, 0x20, 0xa0, 0xe9, 0xa3, 0x3a, 0x94, 0x7d, 0xc2, 0x86, 0x13, 0x1a, 0x71, 0x1a, 0x06, 0x5a,
	0xa6, 0xae, 0x34, 0x4a, 0xf6, 0x32, 0x25, 0x8e, 0x4e, 0x19, 0x99, 0x88, 0xa3, 0xd9, 0xf8, 0xa8,
	0x80, 0xa6, 0x8f, 0x10, 0xe4, 0xee, 0x68, 0xe0, 0x6b, 0x39, 0x79, 0x46, 0xae, 0x05, 0xc7, 0x22,
	0x32, 0xd4, 0xf2, 0x31, 0x27, 0xd6, 0xa8, 0x0a, 0xf9, 0xc8, 0x9b, 0x78, 0x63, 0xad, 0x50, 0x57,
	0x1a, 0x9b, 0x76, 0x0c, 0xd0, 0x6b, 0x80, 0xe1, 0x84, 0x78, 0x9c, 0xf8, 0xae, 0xc7, 0xb5, 0x62,
	0x5d, 0x69, 0x94, 0x5b, 0x35, 0x1c, 0x9b, 0xc1, 0x33, 0x33, 0xb8, 0x3f, 0x73, 0x6b, 0x97, 0x12,
	0x75, 0x9b, 0xeb, 0x18, 0xb6, 0x4f, 0x24, 0x10, 0xd6, 0x6c, 0xf2, 0x69, 0x4a, 0x18, 0x47, 0xcf,
	0x20, 0x27, 0x2c, 0x49, 0x7b, 0xe5, 0x56, 0x1e, 0xcb, 0x3d, 0x49, 0xe9, 0x2f, 0x00, 0x2d, 0xeb,
	0x59, 0x14, 0x06, 0x8c, 0xac, 0x4d, 0x89, 0xbe, 0x0f, 0x5b, 0x1d, 0xc2, 0x97, 0x63, 0xaf, 0x95,
	0x1e, 0x42, 0x65, 0x2e, 0x4d, 0xc2, 0xfe, 0xe2, 0x1d, 0x3f, 0x94, 0xb9, 0x9c, 0xfd, 0x2e, 0xf4,
	0xdf, 0x28, 0x4c, 0xba, 0x04, 0x85, 0x3f, 0x28, 0x01, 0xda, 0x85, 0x42, 0x78, 0x7d, 0xcd, 0x48,
	0x5c, 0xb9, 0xac, 0x9d, 0x20, 0x51, 0xeb, 0x7b, 0x3a, 0xa6, 0x5c, 0xdb, 0x90, 0x74, 0x0c, 0x74,
	0x03, 0xd4, 0x85, 0xef, 0x24, 0x4f, 0x55, 0xc8, 0x0f, 0xc3, 0x69, 0xc0, 0x13, 0xdb, 0x31, 0x40,
	0x7b, 0x90, 0x17, 0xfe, 0x99, 0x96, 0xa9, 0x67, 0x17, 0xe9, 0x8b, 0x39, 0xdd, 0x80, 0xed, 0x41,
	0xe4, 0x3f, 0xaa, 0xfb, 0xda, 0x04, 0x2e, 0xa5, 0x27, 0xb3, 0x9c, 0x1e, 0xbd, 0x21, 0x5f, 0x73,
	0x4e, 0x03, 0x3f, 0xf5, 0x1a, 0x91, 0x26, 0xa6, 0x29, 0xf5, 0x6c, 0xa3, 0x64, 0xc7, 0x40, 0x3f,
	0x80, 0xea, 0x29, 0x65, 0x91, 0xc7, 0x87, 0x37, 0xa9, 0xa2, 0xcd, 0x92, 0xa9, 0x2c, 0x92, 0xa9,
	0xef, 0x03, 0xd8, 0xc4, 0xf3, 0x1f, 0xa4, 0x70, 0xe1, 0x43, 0x59, 0xf5, 0x71, 0xf0, 0x5d, 0x81,
	0x9c, 0xb8, 0x1e, 0xa9, 0xb0, 0x39, 0xb0, 0xce, 0xad, 0xde, 0x7b, 0xcb, 0x3d, 0x37, 0xad, 0x53,
	0xf5, 0x1f, 0x54, 0x05, 0xf5, 0xd8, 0xec, 0x9a, 0xe2, 0xcf, 0x75, 0xcc, 0x8e, 0xe5, 0x9a, 0x96,
	0xaa, 0xa4, 0xd8, 0x63, 0xf7, 0xa4, 0x37, 0xb0, 0xfa, 0x6a, 0x06, 0x55, 0xa0, 0xec, 0xf4, 0x3b,
	0x73, 0x59, 0x56, 0x84, 0x7b, 0xd7, 0x32, 0x3e, 0xcc, 0x99, 0x1c, 0x2a, 0x43, 0xd1, 0x6e, 0x5f,
	0xbe, 0x6d, 0x1b, 0x5d, 0x35, 0x2f, 0x81, 0xd1, 0x35, 0xda, 0x8e, 0xa1, 0x16, 0x10, 0x82, 0xad,
	0xb3, 0x81, 0x71, 0x66, 0x5a, 0xae, 0x43, 0x47, 0x81, 0x50, 0x17, 0xc5, 0xf9, 0x84, 0x8b, 0xaf,
	0xd8, 0x58, 0x62, 0x2e, 0x7b, 0xa6, 0xd5, 0x57, 0x4b, 0x68, 0x07, 0x2a, 0x33, 0x4d, 0xbb, 0x6b,
	0x58, 0xa7, 0x6d, 0x5b, 0x05, 0x11, 0xec, 0x64, 0xe0, 0xf4, 0x7b, 0x17, 0xee, 0x85, 0xe1, 0x38,
	0xed, 0x8e, 0xa1, 0x96, 0x5b, 0xdf, 0x32, 0x50, 0x16, 0xa6, 0x1d, 0x32, 0xf9, 0x4c, 0x87, 0x04,
	0x1d, 0x01, 0x2c, 0x86, 0x10, 0x21, 0xbc, 0x32, 0xc1, 0xb5, 0x1d, 0xfc, 0xc4, 0x94, 0x1e, 0x42,
	0x31, 0x69, 0x1d, 0x54, 0xc1, 0xe9, 0xb1, 0xac, 0xa9, 0xf8, 0xf1, 0xf0, 0x35, 0x61, 0x63, 0xd6,
	0x68, 0x68, 0xbe, 0x3b, 0x2b, 0x5b, 0x6d, 0x1b, 0xaf, 0x74, 0xe1, 0x2b, 0x80, 0x45, 0x4b, 0x21,
	0x84, 0x57, 0xfa, 0xab, 0xb6, 0xbb, 0x32, 0x10, 0x86, 0xf8, 0x81, 0x45, 0x47, 0xf2, 0x2a, 0xd9,
	0x45, 0x68, 0x8d, 0x26, 0xbe, 0x30, 0xdd, 0x68, 0x6f, 0xe0, 0xdf, 0x54, 0x4b, 0xa1, 0xff, 0xf0,
	0x53, 0x2d, 0xb6, 0xee, 0xda, 0xe3, 0x83, 0x8f, 0x8d, 0x11, 0xe5, 0x37, 0xd3, 0x2b, 0x3c, 0x0c,
	0xc7, 0xcd, 0x5b, 0xff, 0xcb, 0x6d, 0x93, 0xd1, 0x51, 0xd0, 0xa4, 0x01, 0x27, 0x93, 0xc0, 0xbb,
	0x8f, 0xbf, 0x03, 0xf2, 0x0b, 0x72, 0x55, 0x90, 0xeb, 0x97, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0xda, 0x81, 0xd3, 0xcb, 0x55, 0x06, 0x00, 0x00,
}
